baseURL = "https://UltraSheep.github.io/"
title = "Sheeps's Blog"
paginate = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "G-W3RBT2SNTC"

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "ExampleSite"
description = "fukfukfukfukfukfukufkukfku"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = true
hidemeta = false
hideSummary = false
showtoc = true
tocopen = true
TocSide = 'left'
PygmentsCodeFences = true
PygmentsStyle = "vim"

  [params.assets]
  favicon = "<link / abs url>"
  favicon16x16 = "<link / abs url>"
  favicon32x32 = "<link / abs url>"
  apple_touch_icon = "<link / abs url>"
  safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "Blog"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = true
  title = "Def not copypasta"
  subtitle = "fuck i deleted all my code(everything including homework)"
  imageUrl = "img/author.jpg"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "my image"
  
  [params.homeInfoParams]
  Title = "Please send help"
  Content = "i found some files back in edit history"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/UltraSheep"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = false
  hiddenInList = true
  hiddenInSingle = true


  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[outputs]
home = [ "HTML", "RSS", "JSON" ]
